### ISSUE TITLE
Look and feel of the post page

### ISSUE THREAD

**Issue by matDobek** [CandN/CandN.github.io#14]
In my humble opinion, the `post` page starts to look messy:

(before adding Disqus:)
![image](https://cloud.githubusercontent.com/assets/4257729/14100856/d04d982c-f590-11e5-93aa-2caa91422eaf.png)

(I really like the way image ended with page)

(after Disqus:)
![image](https://cloud.githubusercontent.com/assets/4257729/14100966/6f9f6a9a-f591-11e5-8212-04275466f752.png)

(more images = more distractions)

Before we had this nice minimalistic look.

Some options:
- add sharing via reddit, where our discussion will happen(instead of Disqus)
- remove github avatar(and leave just the name)

Thoughts?

**Comment by siepet** [comment]
Why not just do, smaller text, under the post title, something similar to:
`matDobek on << date here >>`? We would have an author and a date near the title.

**Comment by matDobek** [comment]
:+1: will give it a try

**Comment by matDobek** [comment]
1.
![image](https://cloud.githubusercontent.com/assets/4257729/14134235/c9410ada-f655-11e5-8154-e7ec1f8b25d2.png)

---

2.
![image](https://cloud.githubusercontent.com/assets/4257729/14134248/e7fe4cee-f655-11e5-8263-7a35b6330007.png)

---

3.
![image](https://cloud.githubusercontent.com/assets/4257729/14134259/09119300-f656-11e5-9589-9554d52e03be.png)

---

4.
![image](https://cloud.githubusercontent.com/assets/4257729/14134347/e3a71364-f656-11e5-8e5e-c203f7385469.png)

---

5.
![image](https://cloud.githubusercontent.com/assets/4257729/14134468/c3b5af24-f657-11e5-8137-11ca830ed535.png)

**Comment by matDobek** [comment]
lets vote or something:

I'll go with something like 4 > 2 > 3

**Comment by siepet** [comment]
Okay, for me 5th also looks okay, but how are you gonna differentiate the signature from the post?

**Comment by naliwajek** [comment]
My votes from most beloved to hated :cat: 3 > 4 > 2 > 1 > 5
